services:

  mysql:
    image: mysql:9.7
    container_name: mysql-container
    ports:
      - "3606:3606"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql-data:/var/lib/mysql

      # Bind Mount: Store MySQL data in a custom location on Ubuntu
      # - /home/ubuntu/volumes/mysql:/var/lib/mysql

      # Bind Mount: Store MySQL data inside the project directory
      # - ./mysql-data:/var/lib/mysql
     
    networks:
      - two-tier
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  flask-app:
    build:
      context: .
    container_name: flask-container
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql    # Should be service_Name not conatiner_Name.
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    depends_on:
       mysql:
          condition: service_healthy
    networks:
      - two-tier
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


networks:
  two-tier:

volumes:
  mysql-data:
